set.seed(1)
setwd("~/../Git/BART-RDD/")
cex = 0.75
bty="L"
# Without W------------------------------------------------
n <- 75
x <- runif(n,-0.5,0.5)
x <- sort(x)
treated <- x >= 0
y <- x^3 -2*x^2 + x + 0.5*treated + rnorm(n,0,0.1)
pdf("Figures/1d_tree_1a.pdf")
plot(x,y,bty=bty,xlab="X",ylab="Y",cex=cex,cex.axis=cex,cex.lab=cex,
     pch = 21 + 3*treated,bg=ifelse(treated,"black","white"))
abline(v=0,lty=3)
abline(v=-0.06,lty=2)
abline(v=0.06,lty=2)
abline(v=x[42],lty=1)
segments(x0=min(x),x1=x[42],y0=mean(y[x< 0]),col="red")
segments(x0=min(x),x1=x[42],y0=mean(y[x> 0 & x<x[42]]),col="blue")
segments(x0=x[42],x1=max(x),y0=mean(y[x> 0]),col="blue")
dev.off()
mean(y[x>0 & x<x[42]])-mean(y[x<0])
pdf("Figures/1d_tree_1b.pdf")
plot(x,y,bty=bty,xlab="X",ylab="Y",cex=cex,cex.axis=cex,cex.lab=cex,
     pch = 21 + 3*treated,bg=ifelse(treated,"black","white"))
abline(v=0,lty=3)
abline(v=-0.06,lty=2)
abline(v=0.06,lty=2)
abline(v=x[24],lty=1)
segments(x0=min(x),x1=x[24],y0=mean(y[x< x[24]]),col="red")
segments(x0=x[24],x1=max(x),y0=mean(y[x> x[24] & x<0]),col="red")
segments(x0=x[24],x1=max(x),y0=mean(y[x> 0]),col="blue")
dev.off()
mean(y[x>0])-mean(y[x > x[24] & x<0])
pdf("Figures/1d_tree_1c.pdf")
plot(x,y,bty=bty,xlab="X",ylab="Y",cex=cex,cex.axis=cex,cex.lab=cex,
     pch = 21 + 3*treated,bg=ifelse(treated,"black","white"))
abline(v=0,lty=3)
abline(v=-0.06,lty=2)
abline(v=0.06,lty=2)
abline(v=x[24],lty=1)
abline(v=x[53],lty=1)
segments(x0=min(x),x1=x[24],y0=mean(y[x< x[24]]),col="red")
segments(x0=x[24],x1=x[53],y0=mean(y[x> x[24] & x<0]),col="red")
segments(x0=x[24],x1=x[53],y0=mean(y[x> 0 & x<x[53]]),col="blue")
segments(x0=x[53],x1=max(x),y0=mean(y[x>x[53]]),col="blue")
dev.off()
mean(y[x>0 & x<x[53]])-mean(y[x>x[24] & x<0])
pdf("Figures/1d_tree_1d.pdf")
plot(x,y,bty=bty,xlab="X",ylab="Y",cex=cex,cex.axis=cex,cex.lab=cex,
     pch = 21 + 3*treated,bg=ifelse(treated,"black","white"))
abline(v=0,lty=3)
abline(v=-0.06,lty=2)
abline(v=0.06,lty=2)
abline(v=x[24],lty=1)
abline(v=x[46],lty=1)
abline(v=x[9],lty=1)
abline(v=x[4],lty=1)
abline(v=x[16],lty=1)
segments(x0=min(x),x1=x[4],y0=mean(y[x< x[4]]),col="red")
segments(x0=x[4],x1=x[9],y0=mean(y[x> x[4] & x< x[9]]),col="red")
segments(x0=x[9],x1=x[16],y0=mean(y[x> x[9] & x< x[16]]),col="red")
segments(x0=x[16],x1=x[24],y0=mean(y[x> x[16] & x< x[24]]),col="red")
segments(x0=x[24],x1=x[46],y0=mean(y[x> x[24] & x<0]),col="red")
segments(x0=x[24],x1=x[46],y0=mean(y[x>0 & x<x[46]]),col="blue")
segments(x0=x[46],x1=max(x),y0=mean(y[x>x[46]]),col="blue")
dev.off()
mean(y[x>0 & x<x[46]])-mean(y[x>x[24] & x<0])
# With W---------------------------------------------------
# set.seed(1)
# x <- runif(n, -1, 1)
# w <- runif(n, -1, 1)
# treated <- x >= 0
# # First split, but opct is not satisfied
# pdf("Figures/bad_trees_1a.pdf")
# plot(x, w, pch = 21 + 3*treated,bg=ifelse(treated,"black","white"),col=1,
#      cex = cex, cex.axis=cex, cex.lab=cex, xlab="X", ylab="W")
# abline(v = -0.25, lty = 2)
# abline(v = 0, lty = 3)
# abline(v = 0.25, lty = 2)
# abline(h = -0.3)
# dev.off()
# # A split that would not meet the first constraint 
# col <- (x > -0.25) & (x < 0) & (w > -0.3) & (w < 0.4)
# pdf("Figures/bad_trees_1b.pdf")
# plot(x, w, pch = 21 + 3*treated,bg=ifelse(treated,"black",ifelse(col,"red","white")),col=1,
#      cex = cex, cex.axis=cex, cex.lab=cex, xlab="X", ylab="W")
# abline(v = -0.25, lty = 2)
# abline(v = 0, lty = 3)
# abline(v = 0.25, lty = 2)
# abline(h = -0.3)
# abline(h = 0.25)
# dev.off()
# # Splits that are likely to happen to satisfy opct
# pdf("Figures/bad_trees_1c.pdf")
# plot(x, w, pch = 21 + 3*treated,bg=ifelse(treated,"black","white"),col=1,
#      cex = cex, cex.axis=cex, cex.lab=cex, xlab="X", ylab="W")
# abline(v = -0.25, lty = 2)
# abline(v = 0, lty = 3)
# abline(v = 0.25, lty = 2)
# abline(h = -0.3)
# abline(v = -0.4)
# dev.off()
# pdf("Figures/good_tree_1.pdf")
# plot(x, w, pch = 21 + 3*treated,bg=ifelse(treated,"black","white"),col=1,
#      cex = cex, cex.axis=cex, cex.lab=cex, xlab="X", ylab="W")
# abline(v = -0.25, lty = 2)
# abline(v = 0, lty = 3)
# abline(v = 0.25, lty = 2)
# abline(h = -0.3)
# abline(v = -0.4)
# abline(v = 0.4)
# dev.off()