* Code for the XBCF-RDD paper
The analysis performed in this paper consists of:
** Simulation experiments
We compare the performance of XBCF-RDD with the following
methods:
1. [[https://www.cambridge.org/core/services/aop-cambridge-core/content/view/339D96B3F14F48A6B51AEC6DE9C16131/S0266466622000019a.pdf/nonparametric_bayes_analysis_of_the_sharp_and_fuzzy_regression_discontinuity_designs.pdf][Nonparametric bayes analysis of the sharp and fuzzy
   regression discontinuity designs - Chib, Greenberg and
   Simoni (2014)]]
2. [[https://academic.oup.com/ectj/advance-article/doi/10.1093/ectj/utac029/6957254][Inference in regression discontinuity designs with
   high-dimensional covariates - Kreiss and Rothe (2022)]]
3. [[https://www.tandfonline.com/doi/full/10.1080/07350015.2017.1421544][Including Covariates in the Regression Discontinuity
   Design - Frolich and Huber (2019)]]

First, we consider the simulated DGPs studied by each of
those papers. The ~simulations.R~ script runs this
analysis. The scripts named ~simulations_x.R~ obtain the
LATE point estimate and 95% intervals for each method in
~x=("xbcf-rdd","cgs","kr","fh")~ for each one of the DGPs
above. The script ~simulations_setup.R~ defines helper
functions for some of the methods and functions to generate
each of the DGPs above. Finally, the script ~FH.R~ defines
the functions to obtain the LATE as in [[https://www.tandfonline.com/doi/full/10.1080/07350015.2017.1421544][Frolich and Huber
(2019)]].

The original code from each of those papers can be found on[fn:1]:
1. [[http://apps.olin.wustl.edu/faculty/chib/rpackages/rdd/][Chib, Greenberg and Simoni R package]]
2. [[https://github.com/akreiss/HighDimRD/blob/master/README.md][Kreiss and Rothe code]]
3. [[https://www.researchgate.net/publication/326649436_R_code_for_Including_covariates_in_the_regression_discontinuity_design][Frolich and Huber code]]
** Data reanalysis
To discuss implementation of XBCF-RDD to real datasets we
perform a reanalysis of the data studied by [[https://www.aeaweb.org/articles?id=10.1257/aer.20190759][Ambrus, Field
and Gonzalez (2020)]]. We focus on their investigation about
the impact of a cholera outbreak in 1854 London on housing
prices in the vicinity of a `contamination area' defined by
the distance to a contaminated water pump. The previous link
contains the paper, data and code for their analysis. From
that, we only study the ~Merged_1853_1864_data.dta~
dataset.
* Footnotes

[fn:1] It is worth noting that the method of CGS is only
made available through Windows and Mac binary files of their
R package on Siddhartha Chib's webpage. Since the package is
not available in CRAN as of yet, this means the package
cannot be compiled on Linux. This is why we check the OS in
the simulation scripts before running each method. CGS was
run on a Windows machine while all the others were run on a
Linux machine
